services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - TERRAIN_MAP_PATH=/data/eudem_slop_3035_europe.tif
    volumes:
      - ./backend/eud_cp_slop:/data:ro

  frontend:
    build:
      context: ./frontend
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
